import Link from "next/link"
import { PageHeader, PAGE_SHELL } from "@/components/page-header"
import { EditorialSection, ContactBand } from "@/components/editorial"
import { COMPANY } from "@/lib/company"
import { TIMELINE } from "@/content/timeline"
import { loadProjects } from "@/lib/content/load"
import { pageMetadata } from "@/lib/metadata"
export const metadata=pageMetadata("About", "NCC Infraspace Private Limited builds infrastructure across India. Discover our origins in 1987, working approach, company structure and project footprint.", "/about")
export default function About(){const states=[...new Set(loadProjects().map(p=>p.state))].sort();return <div className={PAGE_SHELL}>
<PageHeader eyebrow="About NCC" title={<>Experience forms<br/>our foundations.</>} intro="NCC Infraspace Private Limited is an infrastructure contractor working across India. Founded as Natraj Construction Company in 1987, the business became a private limited company in 2015."/>
<EditorialSection label="Identity" title="A company built through its work."><p>From highways and bridges to urban roads and water networks, NCC works with government departments, municipal corporations, development authorities and private clients.</p><dl className="identity-grid">{[["Legal name",COMPANY.legalName],["Established","1987"],["Incorporated","9 April 2015"],["CIN",COMPANY.cin]].map(([k,v])=><div key={k}><dt className="eyebrow">{k}</dt><dd>{v}</dd></div>)}</dl></EditorialSection>
<EditorialSection label="Our approach" title="Responsibility at every stage." dark><div className="approach-list">{[["Quality throughout","Quality is a priority at every stage of the project, from the work on site to delivery."],["Programme and budget","Management oversees execution within the contract’s specified budget and timeframe."],["Engineering on site","Qualified engineers and technical staff carry out project execution." ]].map(([title,body])=><div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></EditorialSection>
<EditorialSection label="History" title="From 1987 to today."><ol className="history-list">{TIMELINE.map(t=><li key={t.year}><span className="measurement">{t.year}</span><div><h3>{t.title}</h3>{t.body&&<p>{t.body}</p>}</div></li>)}</ol></EditorialSection>
<EditorialSection label="Company structure" title="From management to the site."><p>NCC is a private limited company. Its management oversees programme and budget, supported by qualified engineers and technical staff responsible for project execution.</p><div className="structure-line"><span>Management</span><span aria-hidden>↓</span><span>Engineers & technical staff</span><span aria-hidden>↓</span><span>Project execution</span></div></EditorialSection>
<EditorialSection label="Our vision" title="The standard we work towards." dark><blockquote>Striving for perfection in order to establish a prominent position, by exemplary performance, state of art quality work, thereby providing almost satisfaction to all the stakeholders</blockquote></EditorialSection>
<EditorialSection label="Geographic footprint" title="Across India. Grounded in experience."><p>NCC takes on infrastructure work across India. The completed portfolio includes contracts in the following states.</p><ul className="footprint-list">{states.map(s=><li key={s}><span className="route-dot"/>{s}</li>)}</ul><p className="small-note">Project locations describe the completed portfolio. They are not a boundary on where NCC can work.</p><Link className="text-link" href="/projects">Explore the portfolio ↗</Link></EditorialSection><ContactBand/></div>}
